name: flutter_task
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: lib/assets/fonts/Cairo-Regular.ttf
        - asset: lib/assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Cairo-Light.ttf
          weight: 300
